FROM node:19.5.0-alpine

WORKDIR /urs/src/api

COPY . .
COPY ./.env.production ./.en

RUN npm install --quiet --no-optional --no-found --loglevel=error
RUN npm run build

EXPOSE 3000

CMD [ "npm", "run", "start:prod" ]
